### ISSUE TITLE
Add feature to execute TypeScript test file directly.

### ISSUE THREAD

**Issue by shoma-mano** [shoma-mano/maests#4]
Currently, we need to convert the TypeScript file to YAML in order to run the test. It would be much more convenient if we could execute the test directly without having to run the Maestro command separately, something like:
`npx maests sample-flow.ts`

**Comment by shoma-mano** [comment]
@irhlab49
 How do you think about this idea?

**Comment by irhlab49** [comment]
@shoma-mano i really like this idea!!!

BTW, hope you don’t mind when I was flying today for 7 hours I refactored some things. I also added unit tests for commands. I’ll raise a PR on Monday :)

**Comment by shoma-mano** [comment]
@irhlab49 
>  I also added unit tests for commands. I’ll raise a PR on Monday :)

I was just about to do this! I'm looking forward to PR!
